#pragma once

#include "aria/internal/types.hpp"
#include "aria/internal/compiler/core/string_view.hpp"

#include <variant>

namespace Aria::Internal {

    struct TypeInfo;

    enum class VMTypeKind {
        Invalid = 0,
        Void,
        I1,
        I8, U8,
        I16, U16,
        I32, U32,
        I64, U64,
        F32, F64,
        Ptr
    };

    struct VMType {
        VMTypeKind Kind = VMTypeKind::Invalid;

        bool operator==(VMType other) {
            return Kind == other.Kind;
        }
    };

    enum class OpCodeKind {
        Nop,

        Alloca,
        Store,
        Dup,

        PushSF,
        PopSF,

        Ldc,

        Deref,

        DeclareGlobal,
        DeclareLocal,
        DeclareArg,

        LdGlobal,
        LdLocal,
        LdOffset,
        LdArg,
        LdFunc,

        LdPtrGlobal,
        LdPtrLocal,
        LdPtrOffset,
        LdPtrArg,
        LdPtrRet,

        Function,
        Label,
        Jmp,
        Jt,
        Jf,

        Call,
        Ret,

        Neg,

        Add,
        Sub,
        Mul,
        Div,
        Mod,

        And,
        Or,
        Xor,

        Cmp,
        Ncmp,
        Lt,
        Lte,
        Gt,
        Gte,

        // NOTE: These were generated by macros and then inlined
        // CastI8ToI8,
        // CastI8ToI16,
        // CastI8ToI32,
        // CastI8ToI64,
        // CastI8ToU8,
        // CastI8ToU16,
        // CastI8ToU32,
        // CastI8ToU64,
        // CastI8ToF32,
        // CastI8ToF64,
        // 
        // CastI16ToI8,
        // CastI16ToI16,
        // CastI16ToI32,
        // CastI16ToI64,
        // CastI16ToU8,
        // CastI16ToU16,
        // CastI16ToU32,
        // CastI16ToU64, 
        // CastI16ToF32, 
        // CastI16ToF64, 
        // 
        // CastI32ToI8,
        // CastI32ToI16,
        // CastI32ToI32,
        // CastI32ToI64,
        // CastI32ToU8,
        // CastI32ToU16,
        // CastI32ToU32,
        // CastI32ToU64, 
        // CastI32ToF32, 
        // CastI32ToF64, 
        // 
        // CastI64ToI8,
        // CastI64ToI16,
        // CastI64ToI32,
        // CastI64ToI64,
        // CastI64ToU8,
        // CastI64ToU16,
        // CastI64ToU32,
        // CastI64ToU64,
        // CastI64ToF32,
        // CastI64ToF64,
        // 
        // CastU8ToI8,
        // CastU8ToI16,
        // CastU8ToI32,
        // CastU8ToI64,
        // CastU8ToU8,
        // CastU8ToU16,
        // CastU8ToU32,
        // CastU8ToU64,
        // CastU8ToF32,
        // CastU8ToF64,
        // 
        // CastU16ToI8,
        // CastU16ToI16,
        // CastU16ToI32,
        // CastU16ToI64,
        // CastU16ToU8,
        // CastU16ToU16,
        // CastU16ToU32,
        // CastU16ToU64,
        // CastU16ToF32,
        // CastU16ToF64,
        // 
        // CastU32ToI8,
        // CastU32ToI16,
        // CastU32ToI32,
        // CastU32ToI64,
        // CastU32ToU8,
        // CastU32ToU16,
        // CastU32ToU32,
        // CastU32ToU64,
        // CastU32ToF32,
        // CastU32ToF64,
        // 
        // CastU64ToI8,
        // CastU64ToI16,
        // CastU64ToI32,
        // CastU64ToI64,
        // CastU64ToU8,
        // CastU64ToU16,
        // CastU64ToU32,
        // CastU64ToU64,
        // CastU64ToF32,
        // CastU64ToF64,
        // 
        // CastF32ToI8,
        // CastF32ToI16,
        // CastF32ToI32,
        // CastF32ToI64,
        // CastF32ToU8,
        // CastF32ToU16,
        // CastF32ToU32,
        // CastF32ToU64,
        // CastF32ToF32,
        // CastF32ToF64,
        // 
        // CastF64ToI8,
        // CastF64ToI16,
        // CastF64ToI32,
        // CastF64ToI64,
        // CastF64ToU8,
        // CastF64ToU16,
        // CastF64ToU32,
        // CastF64ToU64,
        // CastF64ToF32,
        // CastF64ToF64,

        Cast,

        Comment // Used only for debugging
    };

    #undef TYPED_OP

    struct OpCodeLdc {
        std::variant<bool, i8, u8, i16, u16, i32, u32, i64, u64, f32, f64, StringView> Data;
        VMType Type;
    };

    struct OpCodeCall {
        size_t ArgCount = 0;
        VMType ReturnType;
    };

    struct OpCode {
        OpCodeKind Kind = OpCodeKind::Nop;
        std::variant<size_t, std::string, VMType, OpCodeLdc, OpCodeCall> Data;
    };

} // namespace Aria::Internal
